"""
Hello world! This file has fun with ANSI escape sequences.

"""
for int in range(5000000):
    print("\033[1;31m" + "CAMERON REDOVIAN CAMERON REDOVIAN CAMERON REDOVIAN CAMERON REDOVIAN" + "\033[0m")
    print("\033[1;32m" + "CAMERON REDOVIAN CAMERON REDOVIAN CAMERON REDOVIAN CAMERON REDOVIAN" + "\033[0m")
    print("\033[1;33m" + "CAMERON REDOVIAN CAMERON REDOVIAN CAMERON REDOVIAN CAMERON REDOVIAN" + "\033[0m")
    print("\033[1;34m" + "CAMERON REDOVIAN CAMERON REDOVIAN CAMERON REDOVIAN CAMERON REDOVIAN" + "\033[0m")
    print("\033[1;35m" + "CAMERON REDOVIAN CAMERON REDOVIAN CAMERON REDOVIAN CAMERON REDOVIAN" + "\033[0m")
    print("\033[1;36m" + "CAMERON REDOVIAN CAMERON REDOVIAN CAMERON REDOVIAN CAMERON REDOVIAN" + "\033[0m")
    print("\033[1;37m" + "CAMERON REDOVIAN CAMERON REDOVIAN CAMERON REDOVIAN CAMERON REDOVIAN" + "\033[0m")
